### ISSUE TITLE
Load json::value from file

### ISSUE THREAD

**Issue by HadesD** [artyom-beilis/cppcms#26]
I have a `manifest.json` file like this:
```json
{
  "js/app.js": "js/app.112sf342isw1.js"
}
```
I'm trying to read it by `ostream` in **cppcms::json::value** but it not work:
```cpp
const std::string urlPath = "js/app.js";
std::ifstream f("manifest.json");
cppcms::json::value v;
v.load(f);
std::cout << v[urlPath].str() << std::endl; // It throw exception not found the key
std::cout << v.at(urlPath).str() << std::endl; // also not found exception
```
I think the json file has a `.` in key string, so it can not parse correctly. But i don't know how to solve this issue.

**Comment by artyom-beilis** [comment]
1. `v.load(f)` is not valid code it should be v.load(f,true) or v.load(f,false)
2. Check that f is actually opened and that load succeed (by checking if v.load() returned true
3. The first line `std::cout << v[urlPath].str() << std::endl` in your sample code works (I checked it)
4. Second will not work because at() assumes that key are "." separated - this is kind search by path. If you want keys to include "." you need to access using `operator[]`

**Comment by artyom-beilis** [comment]
Closing as invalid
