### ISSUE TITLE
submit post text is null when header contain content-type 

### ISSUE THREAD

**Issue by edwinbest** [artyom-beilis/cppcms#27]
issue found in http_request.cpp, method int request::on_content_progress(size_t n),  at line 357

if (!f->has_mime())  is error, right way is  Judgment file type， please author affirm

**Comment by artyom-beilis** [comment]
Can you please provide more context to what you are trying to do, example?

In general a form that is submitted via mulitipart/form-data can contain either files (uploaded files) or various post fields - other form data that is being uploaded. This part distinguish between them - is it file - that it has content-type and it needs to be accessed as file.

File has different interface - since files can exceed the size of machine memory. So instead of accessing the data via `http_request::post()` you access it via `http_request::files()`

So what is exact problem are you experiencing - provide full example please.

**Comment by mashomee** [comment]
is it possible we upload a file with various post fields at the same time？

> In general a form that is submitted via mulitipart/form-data can contain **_either_** files (uploaded files) _**or**_ various post fields - other form data that is being uploaded. This part distinguish between them - is it file - that it has content-type and it needs to be accessed as file.

**Comment by edwinbest** [comment]
post fields in header is:

Content-Disposition: form-data; name="uploadfile"; filename="869721020781234_20171226124637.jpg"

Content-Type: image/*; charset=ISO-8859-1

Content-Transfer-Encoding: binary

Content-Disposition: form-data; name="meid"

Content-Type: text/plain; charset=US-ASCII

Content-Transfer-Encoding: 8bit

**Comment by artyom-beilis** [comment]
I still don't understand what is your problem. Provide:

(a) your form
(b) what are you doing exactly... i.e. what do you try to achieve 
(c) what does it mean: "post text is null"

**Comment by HadesD** [comment]
I think that you are using a normal POST form, without `enctype="multipart/form-data"`.
Let try to check it again.

**Comment by edwinbest** [comment]
I using a normal post form,   Because I'm uploading the file, so enctype must be multipart/form-data
Other parameters, such as meid and other parameters, 
The value of the name that cppcms gets to meid is empty，

**Comment by artyom-beilis** [comment]
@edwinbest Once again without you providing full example of your issue, c++ code, html form and so we can't help you.

**Comment by artyom-beilis** [comment]
Closing as not received relevant data
